create table if not exists public.shiprocket_webhook_logs (
  id bigint generated by default as identity primary key,
  shipment_id text,
  status text not null,
  occurred_at timestamptz not null,
  source text not null default 'webhook',
  action text not null default 'applied',
  created_at timestamptz not null default now()
);

create index if not exists idx_shiprocket_webhook_logs_created_at
  on public.shiprocket_webhook_logs (created_at desc);

create index if not exists idx_shiprocket_webhook_logs_shipment
  on public.shiprocket_webhook_logs (shipment_id, created_at desc);
